/* eslint-disable @typescript-eslint/no-unused-vars -- assertion vars exist only to trip the type checker */
/**
 * Type-level assertions for schema/types.ts. Compiled with --strict; the
 * @ts-expect-error lines fail the build if the types ever stop rejecting them.
 * Scratch file — not part of the deliverable.
 */
import type {
  ExerciseTemplate,
  NewExerciseTemplate,
  NewRoutine,
  NewWorkoutSet,
  Patch,
  Routine,
  RoutineDraft,
  SetType,
  WorkoutSet,
  WorkoutVisibility,
  ExerciseHistoryRow,
  ExerciseTotals,
  AppUser,
  Follow,
  NewFollow,
  NewShare,
  Comment,
  CommentNode,
  CommentMention,
  WorkoutLike,
  FollowStatus,
  ShareTarget,
  FollowCounts,
} from "../types";

// --- valid: a catalog row as the driver returns it ------------------------
declare const row: ExerciseTemplate;
const slug: string = row.slug;
const sec: string[] = row.secondary_muscles;
const owner: string | null = row.owner_id;
const archived: Date | null = row.archived_at;
const created: Date = row.created_at;
void [slug, sec, owner, archived, created];

// --- valid: numeric columns are strings, not numbers ----------------------
declare const set: WorkoutSet;
const kg: string | null = set.weight_kg;
const rpe: string | null = set.rpe;
void [kg, rpe];

// --- valid: INSERT shapes omit generated columns --------------------------
const newTemplate: NewExerciseTemplate = {
  slug: "front-squat",
  title: "Front Squat",
  exercise_type: "weight_reps",
  primary_muscle: "quadriceps",
  equipment: "barbell",
};
const newRoutine: NewRoutine = { owner_id: "u", title: "Day C" };
const newSet: NewWorkoutSet = { workout_exercise_id: "we", position: 0, reps: 5, weight_kg: "100.000" };
void [newTemplate, newRoutine, newSet];

// --- valid: Patch makes every mutable column optional ---------------------
const patch: Patch<Routine> = { title: "renamed" };
void patch;

// --- valid: enum unions ---------------------------------------------------
const st: SetType = "dropset";
const vis: WorkoutVisibility = "private";
void [st, vis];

// --- valid: write DTO nests sets without parent ids -----------------------
const draft: RoutineDraft = {
  title: "Day B",
  exercises: [
    { template_id: "t1", superset_key: "A", rest_seconds: 180, sets: [{ reps: 8, weight_kg: "80.000" }] },
  ],
};
void draft;

// --- valid: analytics result shapes --------------------------------------
declare const hist: ExerciseHistoryRow;
const hw: string = hist.workout_id;
const hkg: string | null = hist.weight_kg;
void [hw, hkg];
declare const totals: ExerciseTotals;
const vol: string | null = totals.total_volume_kg;
void vol;

// --- valid: social rows as the driver returns them ------------------------
declare const follow: Follow;
const fs: FollowStatus = follow.status;
const responded: Date | null = follow.responded_at;
const newFollow: NewFollow = { follower_id: "a", followee_id: "b", status: "pending" };
void [fs, responded, newFollow];

declare const like: WorkoutLike;
const likedBy: string = like.user_id;
void likedBy;

declare const comment: Comment;
const parent: string | null = comment.parent_comment_id;
const body: string = comment.body;
void [parent, body];

declare const mention: CommentMention;
const mentioned: string = mention.mentioned_user_id;
void mentioned;

declare const node: CommentNode;
const authorName: string | null = node.author.username;
const replyCount: number = node.replies.length;
void [authorName, replyCount];

// @ts-expect-error username is nullable (collected during profile onboarding)
const badAuthorName: string = node.author.username;

// exclusive arc: exactly one target, expressed in the type
const shareWorkout: NewShare = { token: "Abc123XyZ9q", owner_id: "u", workout_id: "w" };
const shareRoutine: NewShare = { token: "Abc123XyZ9q", owner_id: "u", routine_id: "r" };
const shareFolder: NewShare = { token: "Abc123XyZ9q", owner_id: "u", routine_folder_id: "f" };
void [shareWorkout, shareRoutine, shareFolder];

declare const counts: FollowCounts;
const fc: number = counts.follower_count;
void fc;

const target: ShareTarget = "routine_folder";
void target;

// --- negative cases: these must NOT compile -------------------------------

// @ts-expect-error weight_kg is Numeric (string), not number
const badKg: string | null = set.weight_kg as number;

// @ts-expect-error id is generated by the database and is not accepted on insert
const badNew: NewExerciseTemplate = { id: "x", slug: "s", title: "t", exercise_type: "duration", primary_muscle: "chest", equipment: "none" };

// @ts-expect-error required column missing on insert
const badNew2: NewRoutine = { title: "no owner" };

// @ts-expect-error not a valid set type
const badSetType: SetType = "cluster";

// @ts-expect-error upsert is not a visibility
const badVis: WorkoutVisibility = "unlisted";

// @ts-expect-error exercise_type must come from the enum
const badType: NewExerciseTemplate = { slug: "s", title: "t", exercise_type: "cardio_machine", primary_muscle: "chest", equipment: "none" };

// @ts-expect-error created_at cannot be patched
const badPatch: Patch<AppUser> = { created_at: new Date() };

// @ts-expect-error sets inside a draft carry no parent id
const badDraft: RoutineDraft = { title: "x", exercises: [{ template_id: "t", sets: [{ routine_exercise_id: "re" }] }] };

// @ts-expect-error not a valid follow status
const badFollowStatus: FollowStatus = "requested";

// @ts-expect-error a share with two targets violates the exclusive arc
const badShareTwo: NewShare = { token: "Abc123XyZ9q", owner_id: "u", workout_id: "w", routine_id: "r" };

// @ts-expect-error a share with no target violates the exclusive arc
const badShareNone: NewShare = { token: "Abc123XyZ9q", owner_id: "u" };

// @ts-expect-error not a shareable target kind
const badTarget: ShareTarget = "program";

// @ts-expect-error comment body is required and must be a string
const badComment: Comment = { id: "c", workout_id: "w", author_id: "a", parent_comment_id: null, body: 42, created_at: new Date(), updated_at: new Date() };

export {};
