/**
 * Uploads the exercise videos to Vercel Blob.
 *
 * A repeatable tool rather than a one-off. The videos are 189 MB of source input
 * that must not live in the repository, so any fresh environment needs a way to
 * populate the store — and re-running this is the answer.
 *
 * Slugs come from the database rather than being re-derived here: the import
 * migration is the authority on what each exercise is called, and deriving them
 * a second way is how the two drift apart.
 *
 * Requires BLOB_READ_WRITE_TOKEN. The store must be public: these are videos the
 * browser fetches directly by URL, not through a signed route.
 *
 * Usage:
 *   BLOB_READ_WRITE_TOKEN=... bun run scripts/upload-exercise-videos.ts
 *   ... --dry-run          list what would be uploaded, upload nothing
 *   ... --only=<slug>      upload one exercise
 *   ... --emit-migration   write the 0012 media_url migration, upload nothing
 *
 * A full upload (no `--only`) also rewrites `schema/migrations/0012_*.sql` after
 * every video lands, so the migration records exactly what exists. It is written
 * only when nothing failed: a row claiming a video that was not uploaded is how
 * the app ends up offering a player for a file nothing can serve.
 */
import { put } from "@vercel/blob";
import { readdir, readFile } from "node:fs/promises";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { db } from "../lib/db";

const VIDEO_DIR = join(process.cwd(), "exercises", "vids");
/**
 * Blob path prefix. `media_url` is stored as `${PREFIX}/<slug>.mp4`, a path
 * relative to `NEXT_PUBLIC_MEDIA_BASE_URL`, and the app joins the two.
 */
const PREFIX = "exercise-videos";
const OUT_MIGRATION = join(process.cwd(), "schema", "migrations", "0012_exercise_media_url.sql");

const args = process.argv.slice(2);
const dryRun = args.includes("--dry-run");
const emitMigration = args.includes("--emit-migration");
const only = args.find((a) => a.startsWith("--only="))?.slice("--only=".length) ?? null;

if (emitMigration && only) {
  console.error("--emit-migration writes the whole migration; it cannot be combined with --only.");
  process.exit(1);
}

if (!dryRun && !emitMigration && !process.env.BLOB_READ_WRITE_TOKEN) {
  console.error("BLOB_READ_WRITE_TOKEN is not set. Create the store, connect it, and pass the token.");
  process.exit(1);
}

/**
 * Source filenames are `<Title> [<external id>].mp4`, and the title in the file
 * is the one the import used, so the title is the join between the two.
 */
function findSourceFile(title: string, entries: string[]): string | undefined {
  const prefix = `${title} [`;
  return entries.find((name) => name.startsWith(prefix) && name.endsWith(".mp4"));
}

function quote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

/**
 * Writes the migration that records which videos exist. The uploader is the one
 * component that knows the answer, so it is the one that produces this file —
 * deriving the same list a second way inside the migration is how the two would
 * drift apart. Deterministic (slug-sorted) so re-running produces no diff.
 */
function emitMediaMigration(slugs: string[]): void {
  const values = [...slugs]
    .sort()
    .map((slug) => `  (${quote(slug)}, ${quote(`${PREFIX}/${slug}.mp4`)})`)
    .join(",\n");

  const sql = `-- ---------------------------------------------------------------------------
-- 0012_exercise_media_url.sql — generated by scripts/upload-exercise-videos.ts
--
-- Do not edit by hand. Re-run a full upload, or
-- \`bun run scripts/upload-exercise-videos.ts --emit-migration\`, instead.
--
-- Records which exercises actually have a video in the blob store. Only the
-- slugs whose source file was found are listed, so the exercise page renders a
-- player only where there is something to play. The value is a path relative to
-- the media host (NEXT_PUBLIC_MEDIA_BASE_URL), not a full URL: switching stores
-- stays a configuration change rather than a data migration.
--
-- Idempotent: every row is set to the value it already has, so applying this
-- twice leaves the table unchanged.
-- ---------------------------------------------------------------------------

begin;

update exercise_template as t
set media_url = v.media_url
from (values
${values}
) as v (slug, media_url)
where t.slug = v.slug;

comment on column exercise_template.media_url is
  'Path to the exercise''s demonstration video, relative to NEXT_PUBLIC_MEDIA_BASE_URL. Null when no video has been uploaded.';

commit;
`;

  writeFileSync(OUT_MIGRATION, sql, "utf8");
  console.log(`wrote ${OUT_MIGRATION} (${slugs.length} videos)`);
}

async function main() {
  const entries = await readdir(VIDEO_DIR);

  const rows = await db
    .selectFrom("exercise_template")
    .select(["slug", "title"])
    // Only the shipped catalog: custom exercises are per-user and are not part
    // of the media that this tool publishes, and a user's own title aligning
    // with a source file must not leak into the generated migration.
    .where("is_custom", "=", false)
    .orderBy("title", "asc")
    .execute();

  const targets = only ? rows.filter((r) => r.slug === only) : rows;
  if (targets.length === 0) {
    console.error(only ? `No exercise with slug ${only}.` : "No exercises found — run db:migrate first.");
    process.exit(1);
  }

  let uploaded = 0;
  let skipped = 0;
  const missing: string[] = [];
  const failed: string[] = [];
  /** Slugs whose source file exists — the set the migration records. */
  const published: string[] = [];

  for (const [index, row] of targets.entries()) {
    const file = findSourceFile(row.title, entries);
    if (!file) {
      missing.push(row.title);
      continue;
    }
    published.push(row.slug);

    const label = `[${index + 1}/${targets.length}] ${row.title}`;
    if (dryRun || emitMigration) {
      if (dryRun) console.log(`${label} -> ${PREFIX}/${row.slug}.mp4 (from ${file})`);
      skipped++;
      continue;
    }

    try {
      await put(`${PREFIX}/${row.slug}.mp4`, await readFile(join(VIDEO_DIR, file)), {
        access: "public",
        // The app addresses each video by its slug, so the pathname has to be
        // exactly what it derives. A random suffix would break every URL.
        addRandomSuffix: false,
        contentType: "video/mp4",
      });
      uploaded++;
      console.log(`${label} -> ${PREFIX}/${row.slug}.mp4`);
    } catch (error) {
      failed.push(row.title);
      console.error(`${label} FAILED: ${String(error instanceof Error ? error.message : error).slice(0, 200)}`);
    }
  }

  // `--emit-migration` writes without uploading. A real full upload writes too,
  // but only when every video landed: a partial or failed run must not record a
  // video that is not there. A single-slug `--only` run never writes, because it
  // would replace the whole list with one row.
  if (emitMigration) {
    emitMediaMigration(published);
  } else if (!dryRun && !only && failed.length === 0) {
    emitMediaMigration(published);
  }

  console.log(
    `\n${uploaded} uploaded, ${skipped} listed, ${missing.length} with no source video, ${failed.length} failed`,
  );
  if (missing.length) console.log(`no source video: ${missing.slice(0, 10).join(", ")}${missing.length > 10 ? " …" : ""}`);
  if (failed.length) console.log(`failed: ${failed.slice(0, 10).join(", ")}${failed.length > 10 ? " …" : ""}`);

  await db.destroy();
  process.exit(failed.length ? 1 : 0);
}

await main();
